#include "../../common/LegacyAirwindowsVst3.h"
#include "PitchDelay.h"
#include "public.sdk/source/main/pluginfactory.h"
namespace Steinberg::LVS { namespace { const FUID kProcessorUID(0xD419494C,0xC3A5C5B1,0x43E20BA9,0x71FC23FD); const FUID kControllerUID(0xB5BEB010,0xF915B90D,0xB872B1BF,0x94799BAA); const LegacyParameterSpec kParameters[]={{STR16("Time"),1000,0,0.35,0,LegacyParameterTarget::Legacy,mapInverse},{STR16("Feedback"),1001,1,0.2,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Tone"),1002,2,0.5,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Resonance"),1003,3,0.0,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Pitch"),1004,4,0.5,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Mix"),1005,-1,0.35,0,LegacyParameterTarget::WetMix,mapDirect}}; const LegacyFixedParameter kFixedParameters[]={{5,1.0f}}; AudioEffectX* createLegacyEffect(){return new ::PitchDelay(nullptr);} const LegacyPluginSpec kPluginSpec{&kControllerUID,kParameters,6,kFixedParameters,1,&createLegacyEffect,"PitchDelay.uidesc"}; } class PitchDelayProcessor final:public LegacyEffectProcessor{public:PitchDelayProcessor():LegacyEffectProcessor(kPluginSpec){} static FUnknown* createInstance(void*){return static_cast<Vst::IAudioProcessor*>(new PitchDelayProcessor());}}; class PitchDelayController final:public LegacyEffectController{public:PitchDelayController():LegacyEffectController(kPluginSpec){} static FUnknown* createInstance(void*){return static_cast<Vst::IEditController*>(new PitchDelayController());}}; }
#define stringPluginName "LVS Pitch Delay"
#define FULL_VERSION_STR "0.2.0"
using namespace Steinberg; using namespace Steinberg::Vst; using namespace Steinberg::LVS; BEGIN_FACTORY_DEF("Lyric Video Studio","https://lyricvideo.studio","mailto:support@lyricvideo.studio")
DEF_CLASS2(INLINE_UID_FROM_FUID(kProcessorUID),PClassInfo::kManyInstances,kVstAudioEffectClass,stringPluginName,Vst::kDistributable,"Fx|Delay",FULL_VERSION_STR,kVstVersionString,PitchDelayProcessor::createInstance)
DEF_CLASS2(INLINE_UID_FROM_FUID(kControllerUID),PClassInfo::kManyInstances,kVstComponentControllerClass,stringPluginName " Controller",0,"",FULL_VERSION_STR,kVstVersionString,PitchDelayController::createInstance)
END_FACTORY
