#include "../../common/LegacyAirwindowsVst3.h"
#include "Density3.h"
#include "public.sdk/source/main/pluginfactory.h"
namespace Steinberg::LVS { namespace { const FUID kProcessorUID(0x90CAF450,0x0F547E40,0xCB9595EF,0x315CF8F5); const FUID kControllerUID(0x34FA96AF,0xE1F33084,0xA712A210,0x2DE07779); const LegacyParameterSpec kParameters[]={{STR16("Drive"),1000,0,0.2,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Highpass"),1001,1,0.0,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Output"),1002,2,1.0,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Mix"),1003,3,1.0,0,LegacyParameterTarget::Legacy,mapDirect}}; AudioEffectX* createLegacyEffect(){return new ::Density3(nullptr);} const LegacyPluginSpec kPluginSpec{&kControllerUID,kParameters,4,nullptr,0,&createLegacyEffect,"Saturation.uidesc"}; } class SaturationProcessor final:public LegacyEffectProcessor{public:SaturationProcessor():LegacyEffectProcessor(kPluginSpec){} static FUnknown* createInstance(void*){return static_cast<Vst::IAudioProcessor*>(new SaturationProcessor());}}; class SaturationController final:public LegacyEffectController{public:SaturationController():LegacyEffectController(kPluginSpec){} static FUnknown* createInstance(void*){return static_cast<Vst::IEditController*>(new SaturationController());}}; }
#define stringPluginName "LVS Saturation"
#define FULL_VERSION_STR "0.2.0"
using namespace Steinberg; using namespace Steinberg::Vst; using namespace Steinberg::LVS; BEGIN_FACTORY_DEF("Lyric Video Studio","https://lyricvideo.studio","mailto:support@lyricvideo.studio")
DEF_CLASS2(INLINE_UID_FROM_FUID(kProcessorUID),PClassInfo::kManyInstances,kVstAudioEffectClass,stringPluginName,Vst::kDistributable,"Fx|Distortion",FULL_VERSION_STR,kVstVersionString,SaturationProcessor::createInstance)
DEF_CLASS2(INLINE_UID_FROM_FUID(kControllerUID),PClassInfo::kManyInstances,kVstComponentControllerClass,stringPluginName " Controller",0,"",FULL_VERSION_STR,kVstVersionString,SaturationController::createInstance)
END_FACTORY
