#include "../../common/LegacyAirwindowsVst3.h"
#include "ToTape9.h"
#include "public.sdk/source/main/pluginfactory.h"
namespace Steinberg::LVS { namespace { const FUID kProcessorUID(0x5C8585AC,0x68955483,0xC65CAE6D,0x9962CEEA); const FUID kControllerUID(0x149F1B38,0xBD2E3596,0xD95F33D3,0xB9751723); const LegacyParameterSpec kParameters[]={{STR16("Input"),1000,0,0.5,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Tilt"),1001,1,0.5,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Shape"),1002,2,0.5,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Flutter"),1003,3,0.5,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Flutter Speed"),1004,4,0.5,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Bias"),1005,5,0.5,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Head Bump"),1006,6,0.5,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Head Freq"),1007,7,0.5,0,LegacyParameterTarget::Legacy,mapDirect},{STR16("Output"),1008,8,0.5,0,LegacyParameterTarget::Legacy,mapDirect}}; AudioEffectX* createLegacyEffect(){return new ::ToTape9(nullptr);} const LegacyPluginSpec kPluginSpec{&kControllerUID,kParameters,9,nullptr,0,&createLegacyEffect,"Tape.uidesc"}; } class TapeProcessor final:public LegacyEffectProcessor{public:TapeProcessor():LegacyEffectProcessor(kPluginSpec){} static FUnknown* createInstance(void*){return static_cast<Vst::IAudioProcessor*>(new TapeProcessor());}}; class TapeController final:public LegacyEffectController{public:TapeController():LegacyEffectController(kPluginSpec){} static FUnknown* createInstance(void*){return static_cast<Vst::IEditController*>(new TapeController());}}; }
#define stringPluginName "LVS Tape"
#define FULL_VERSION_STR "0.2.0"
using namespace Steinberg; using namespace Steinberg::Vst; using namespace Steinberg::LVS; BEGIN_FACTORY_DEF("Lyric Video Studio","https://lyricvideo.studio","mailto:support@lyricvideo.studio")
DEF_CLASS2(INLINE_UID_FROM_FUID(kProcessorUID),PClassInfo::kManyInstances,kVstAudioEffectClass,stringPluginName,Vst::kDistributable,"Fx|Distortion",FULL_VERSION_STR,kVstVersionString,TapeProcessor::createInstance)
DEF_CLASS2(INLINE_UID_FROM_FUID(kControllerUID),PClassInfo::kManyInstances,kVstComponentControllerClass,stringPluginName " Controller",0,"",FULL_VERSION_STR,kVstVersionString,TapeController::createInstance)
END_FACTORY
